version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=codeexec
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=password
    ports:
      - "3307:3306"

  app:
    image: codeexec:0.0.2
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/CodeExec"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: codeexec
      DB_PASSWORD: password
      DB_HOST: db


